# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Smekbo
email: dont-have-one@just-dm.me
description: >- # this means to ignore newlines until "baseurl:"
  A jekyll minima based template I spun up to host comics and ???
baseurl: "/comics" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: smekbo
github_username:  smekbo

collections_dir: collections
collections:
  authors:
  wolfwear:
    type: comic
    title: Wolfwear Wearwolf
    authors:
      - nick
      - bob
    description: >-
      A cursed hoodie and an orphan
    sort_by: pagenum
    output: true
    permalink: /:collection/:name
  mushroom:
    type: comic
    title: Mushroom
    authors:
      - bob
    description: >-
      A witch in the forest
      ( <a href="http://latchkeykingdom.com/">
      Latchkey Kingdom</a> fan comic)
    sort_by: pagenum
    output: true
    permalink: /:collection/:name
  animation_portfolio:
    type: portfolio
    title: Animation Portfolio
    authors:
      - bob
    output: true
    permalink: /:collection/:name    

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
paginate: false

feed:
  collections:
    - authors
    - mushroom
    - wolfwear
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
